# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 03:16
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('wagtailimages', '0019_delete_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'listado carreras',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RacePage',
            fields=[
                ('page_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('is_international', models.BooleanField(verbose_name='Internacional')),
                ('distance', models.IntegerField(verbose_name='Distancia (Km)')),
                ('cost_currency',
                 djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $'), ('DOP', 'DOP $')], default='DOP',
                                                     editable=False, max_length=3)),
                ('cost', djmoney.models.fields.MoneyField(currency_choices=(('USD', 'USD $'), ('DOP', 'DOP $')),
                                                          decimal_places=3, default=Decimal('10'),
                                                          default_currency='DOP', max_digits=10, verbose_name='Costo')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('sign_in', models.CharField(max_length=250, verbose_name='Detalles de inscripcción')),
                ('notes', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Informacion adicional')),
                ('city',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.City')),
            ],
            options={
                'verbose_name': 'carrera',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RacePageGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                            to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE,
                                                         related_name='gallery_images', to='events.RacePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RacePageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE,
                                                                   related_name='tagged_items', to='events.RacePage')),
                ('tag',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_racepagetag_items',
                                   to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RaceTagIndexPage',
            fields=[
                ('page_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='racepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True,
                                                                     help_text='A comma-separated list of tags.',
                                                                     through='events.RacePageTag', to='taggit.Tag',
                                                                     verbose_name='Tags'),
        ),
    ]
