# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import djmoney.models.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racepage',
            name='address',
        ),
        migrations.AddField(
            model_name='racepage',
            name='route_description',
            field=wagtail.wagtailcore.fields.RichTextField(default='', verbose_name='Detalles de ruta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='racepage',
            name='cost',
            field=djmoney.models.fields.MoneyField(blank=True, currency_choices=(('USD', 'USD $'), ('DOP', 'DOP $')),
                                                   decimal_places=3, default=None, default_currency='DOP',
                                                   max_digits=10, null=True, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='racepage',
            name='sign_in',
            field=models.CharField(blank=True, max_length=250, verbose_name='Detalles de inscripcción'),
        ),
    ]
