# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0006_auto_20170701_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racepage',
            name='route_description',
            field=models.TextField(blank=True, verbose_name='Detalles de ruta'),
        ),
    ]
