# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('events', '0007_auto_20170701_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceindexpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to='wagtailimages.Image', verbose_name='Imagen Principal'),
        ),
    ]
